# Generated by Django 4.1.4 on 2023-01-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='ism',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='mavzu',
        ),
    ]
