# Generated by Django 4.1.4 on 2023-01-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malumotlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='malumotlar',
            options={'verbose_name': 'malumot', 'verbose_name_plural': 'malumotlar'},
        ),
        migrations.AddField(
            model_name='malumotlar',
            name='linkpicture',
            field=models.CharField(default='https://t3.ftcdn.net/jpg/00/61/40/40/360_F_61404050_Me0Y8GKi4MRsrOKR49ADO5EnEJgv2QtE.jpg', max_length=10000),
        ),
    ]
