# Generated by Django 4.1.4 on 2023-01-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malumotlar', '0002_alter_malumotlar_options_malumotlar_linkpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malumotlar',
            name='linkpicture',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
