# Generated by Django 4.1.4 on 2023-01-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
