# Generated by Django 4.1.4 on 2023-01-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yangiliklar',
            options={'verbose_name': 'malumot', 'verbose_name_plural': 'malumotlar'},
        ),
    ]
