# Generated by Django 4.1.4 on 2023-01-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0002_alter_yangiliklar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yangiliklar',
            options={'verbose_name': 'new', 'verbose_name_plural': 'news'},
        ),
    ]
